### ISSUE TITLE
Crear transformación: Inyección de lógica

### ISSUE THREAD

**Issue by bordio** [marvelek/tadp-2015c2-tp-metaprogramacion#10]
Esta transformación recibe un bloque con una extensión al código del método
original. Cuando el método en cuestión sea invocado, el bloque recibido debe
ejecutarse Antes ("before do ...") , Después  ("after do ...") o En Lugar De ( "instead_of do ...") el código original del método.

Sub issue 1: "before do ..."
Sub issue 2: "after do ..."
Sub issue 3: "instead_of do ..."

**Comment by marvelek** [comment]
Hu me equivoqué de número en el commit del issue, quería referenciar al Issue #8

**Comment by marvelek** [comment]
Jaja soy un boludo, era para el Issue #15
