### ISSUE TITLE
Estrategia de missing_method para incluir mixins

### ISSUE THREAD

**Issue by canofm** [marvelek/tadp-2015c2-tp-metaprogramacion#15]
En Aspectable, hay que crear un missing_method que segun el nombre del metodo, incluya el mixin correspondiente o tire exception de que el método no existe.

**Comment by marvelek** [comment]
Termino siendo muuuy fácil implementar esto!
Sólo hay que hacer un require_relative y un extend
Cuando lo termine de pulir lo commiteo
