### ISSUE TITLE
Crear condición: Selector

### ISSUE THREAD

**Issue by bordio** [marvelek/tadp-2015c2-tp-metaprogramacion#3]
Esta condición se cumple cuando el selector del método respeta una cierta regex.
Es decir, el nombre del método respeta cierta expresión regular. Ej: name(/fo{2}/)

**Comment by marvelek** [comment]
Ya estaba hecho (igual le cambié el nombre y sin querer quedó namely jaj) Como verás es bastante simple jaja

  def namely(regex)
    proc { |a_method| regex.match(a_method) }
  end
