### ISSUE TITLE
Crear transformación: Inyección de parámetro

### ISSUE THREAD

**Issue by bordio** [marvelek/tadp-2015c2-tp-metaprogramacion#8]
Esta Transformación recibe un hash que representa nuevos valores para los
parámetros del método. Al momento de ser invocado, los parámetros con nombres
definidos en el hash deben ser sustituidos por los valores presentes en el mismo.
Es decir, recibe un hash (clave-valor), y reemplaza aquellas claves que coincidan con tal valor.

Sub Issue: Si recibe un Proc como valor, lo que se reemplaza es el resultado de evaluar el Proc, no el Proc en si mismo.

**Comment by marvelek** [comment]
0. Tener la referencia del método posta y hacer un define_aspectable_method(method.mame)
1. Obtener la lista de argumentos con method.parameters.map do |param| param[1] end
2. zip de ese array al array de args* que le pasa el usuario al método
3. Por cada uno de los nombres de argumentos del hash, reemplazar en el array zipeado el valor ingresado por el usuario, por el valor del hash
4. mapear esa lista para obtener, en orden, el array que tiene los valores que ingresó el usuario, y los del hash
5. Ejecutar el método posta pasandole como *args el array del paso anterior
