### ISSUE TITLE
Crear transformación: Redirección

### ISSUE THREAD

**Issue by bordio** [marvelek/tadp-2015c2-tp-metaprogramacion#9]
Esta transformación recibe un objeto sustituto por parámetro. Al momento de ser
invocado el método, en lugar de ser ejecutado sobre el receptor original, debe
ejecutarse sobre el sustituto.
Es decir, recibe un objeto sustituto para cambiar el receptor del mensaje enviado.

**Comment by bordio** [comment]
te odio fede.. ya lo estaba testeando el mío....

**Comment by marvelek** [comment]
Podés testear, commitear y se agrega solo al pr :)

2015-09-18 14:02 GMT-03:00 Ornella <notifications@github.com>:
